server:
  port: 9091


spring:
  application:
    name: weather-forecast-api

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: forecast_db

  mvc:
    problemdetails:
      enabled: true